# Generated by Django 3.0.3 on 2020-03-22 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('megapp', '0002_search_created'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='members',
            new_name='Member',
        ),
    ]
