# Generated by Django 3.0.3 on 2020-03-22 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('megapp', '0003_auto_20200322_0934'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='search',
            options={'verbose_name_plural': 'searches'},
        ),
        migrations.AddField(
            model_name='member',
            name='signed',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
