# Generated by Django 3.0.3 on 2020-03-22 10:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('megapp', '0004_auto_20200322_0942'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='signed',
            new_name='sign_time',
        ),
        migrations.AddField(
            model_name='member',
            name='college',
            field=models.CharField(default=datetime.datetime(2020, 3, 22, 10, 55, 12, 294863, tzinfo=utc), max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='course',
            field=models.CharField(default=datetime.datetime(2020, 3, 22, 10, 55, 19, 235446, tzinfo=utc), max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='email',
            field=models.CharField(default=datetime.datetime(2020, 3, 22, 10, 55, 25, 53732, tzinfo=utc), max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='phone',
            field=models.CharField(default=datetime.datetime(2020, 3, 22, 10, 56, 22, 942079, tzinfo=utc), max_length=500),
            preserve_default=False,
        ),
    ]
