# Generated by Django 3.0.3 on 2020-04-14 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('megapp', '0007_userprofileinfo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofileinfo',
            old_name='portfolio_site',
            new_name='course',
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
